spring:
  # mysql ??
  datasource:
    url: jdbc:mysql://localhost:3306/shoppingmall?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: true
    defer-datasource-initialization: true

  devtools:
    livereload:
      enabled: true

  thymeleaf:
    cache: false

  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org:
      hibernate:
        SQL: trace




